# Generated by Django 5.2 on 2025-08-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vaga', models.CharField(max_length=150, unique=True)),
                ('status', models.CharField(choices=[('ocupado', 'ocupado'), ('livre', 'livre')], max_length=10)),
                ('tipo_vaga', models.CharField(choices=[('pcd', 'pcd'), ('gestor', 'gestor'), ('idoso', 'idoso'), ('comum', 'comum')], max_length=10)),
            ],
        ),
    ]
