# Generated by Django 5.2 on 2025-08-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='status',
            field=models.CharField(choices=[('OCUPADO', 'OCUPADO'), ('LIVRE', 'LIVRE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='tipo_vaga',
            field=models.CharField(choices=[('PCD', 'PCD'), ('GESTOR', 'GESTOR'), ('IDOSO', 'IDOSO'), ('COMUM', 'COMUM')], max_length=10),
        ),
    ]
